# Generated by Django 5.2.1 on 2025-06-07 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0002_recept_ingredience_recept_postup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'ordering': ['nazev'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='kuchar',
            options={'ordering': ['jmeno'], 'verbose_name': 'Kuchař', 'verbose_name_plural': 'Kuchaři'},
        ),
        migrations.AlterModelOptions(
            name='recept',
            options={'ordering': ['-datum_vytvoreni'], 'verbose_name': 'Recept', 'verbose_name_plural': 'Recepty'},
        ),
        migrations.AddField(
            model_name='recept',
            name='cas_pripravy',
            field=models.PositiveIntegerField(default=30, help_text='Čas přípravy v minutách'),
        ),
        migrations.AddField(
            model_name='recept',
            name='obtiznost',
            field=models.CharField(choices=[('L', 'Lehká'), ('S', 'Střední'), ('T', 'Těžká')], default='S', help_text='Obtížnost receptu', max_length=1),
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='nazev',
            field=models.CharField(help_text="Název kategorie, např. 'Hlavní jídla'", max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='kuchar',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografie autora'),
        ),
        migrations.AlterField(
            model_name='kuchar',
            name='jmeno',
            field=models.CharField(help_text='Jméno autora receptu', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='recept',
            name='datum_vytvoreni',
            field=models.DateTimeField(auto_now_add=True, help_text='Datum přidání receptu'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='ingredience',
            field=models.TextField(default='[]', help_text='JSON seznam ingrediencí'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='kategorie',
            field=models.ForeignKey(help_text='Kategorie receptu', on_delete=django.db.models.deletion.CASCADE, related_name='recepty', to='recepty.kategorie'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='kuchar',
            field=models.ForeignKey(help_text='Autor receptu', on_delete=django.db.models.deletion.CASCADE, related_name='recepty', to='recepty.kuchar'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='nazev',
            field=models.CharField(help_text='Název receptu', max_length=200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='recept',
            name='obrazek',
            field=models.ImageField(blank=True, help_text='Obrázek receptu', null=True, upload_to='recepty/'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='popis',
            field=models.TextField(help_text='Krátký popis receptu', validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='recept',
            name='postup',
            field=models.TextField(default='[]', help_text='JSON seznam kroků postupu'),
        ),
    ]
